# Generated by Django 3.2.7 on 2021-11-25 06:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_profile_country'),
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStaff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('user_type', models.CharField(choices=[('pilot', 'Pilot'), ('attendant', 'Attendant')], default='attendant', max_length=250)),
            ],
            options={
                'verbose_name': 'Flight Staff',
                'verbose_name_plural': 'Flight Staff',
            },
            bases=('user.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FlightStaffProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.profile')),
                ('plane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='airport.plane')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight_staff.flightstaff')),
            ],
            options={
                'verbose_name': 'Flight Staff Profile',
                'verbose_name_plural': 'Flight Staff Profiles',
            },
            bases=('user.profile',),
        ),
        migrations.CreateModel(
            name='FlightStaffFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_staff.flightstaff')),
            ],
            options={
                'verbose_name': 'Flight Staff Feedback',
                'verbose_name_plural': 'Flight Staff Feedback',
            },
            bases=('user.feedback',),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('attendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight_staff.flightstaff')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airport.booking')),
            ],
        ),
    ]
