# Generated by Django 3.2.7 on 2021-11-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightstaff',
            name='user_type',
            field=models.CharField(choices=[('pilot', 'Pilot'), ('security', 'Security'), ('maintenance', 'Maintenance'), ('attendant', 'Attendant')], default='attendant', max_length=250),
        ),
    ]
